### ISSUE TITLE
[Gallery][Wasm/iOS/Android/Skia.Gtk]Checkbox(Material)- Box for all checkbox are invisible.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/Uno.Themes#1059]
### Current behavior

![Checkbox issue](https://github.com/unoplatform/uno/assets/74563602/082291e7-9dc0-4e45-90d5-1ea0c40ee1f7)

### Expected behavior

Checkbo should display.

### How to reproduce it (as minimally and precisely as possible)

1. Launch the Uno.Gallery app.
2. Click on “Checkbox” from the "UI Components" list.
3. Go to the 'material' section.
4. Notice that Box for all checkbox option are invisible.

### Works on UWP/WinUI

None

### Affected platforms

WebAssembly, Android, iOS

**Comment by jeromelaban** [comment]
The changes introduced by #1003 are causing issues in the gallery because the material theme is merged before the Fluent styles are applied:

https://github.com/unoplatform/Uno.Gallery/blob/b87de2f0c3b85a643d4ca1d86e368369548e9410/Uno.Gallery/Uno.Gallery.UWP/App.xaml#L10-L28

The effect of this is that the resolution of theme resources from the material checkbox, like :

https://github.com/unoplatform/Uno.Themes/blob/66d109c155259d176108a81e9ff1653daeb672a6/src/library/Uno.Material/Styles/Controls/v2/CheckBox.xaml#L307

which are the same as the ones used by fluent resources, and they get used first because defined last in the app-wide resources.

I don't have a fix for this yet, but it feels like this is a gallery-specific problem, where including app-wide styles it causing a lot of friction and I wonder if we should always be re-importing Material/Fluent/Cupertino resources in all individual tab samples in the gallery.

/cc @kazo0 @agneszitte

**Comment by kazo0** [comment]
@jeromelaban I believe we are also running into strange behaviors because of this in the themes and toolkit sample apps. 

I need to double check but I think I was able to workaround some of it by initializing the MaterialTheme inside of the XamlControlsResources.MergedDictionaries instead of the App's MergedDictionaries

**Comment by jeromelaban** [comment]
@kazo0 indeed. Also, the WinUI app is showing the same behavior, so Uno is aligned properly.

**Comment by sakshi173** [comment]
@agneszitte , do you have any update on this defect, still I am seeing this issue in all platforms.

**Comment by kazo0** [comment]
@sakshi173 this should now be fixed

**Comment by sakshi173** [comment]
@kazo0 this issue is fixed, closing it.
