### ISSUE TITLE
Header Property Content (Text) of ToggleSwitch is not shown if set

### ISSUE THREAD

**Issue by DevTKSS** [unoplatform/Uno.Themes#1511]
### Current behavior

![image](https://github.com/user-attachments/assets/1b857362-3ce0-4d27-84c8-130bbc3c3fbf)
![image](https://github.com/user-attachments/assets/fa78ea5b-afa0-41b6-9cf5-f8fe0cdbd7de)

The Header Text of ToggleSwitch is not displayed if its set as normal:
![image](https://github.com/user-attachments/assets/913d1a8f-f090-4de4-91dc-cc7610b2a8f9)

### Expected behavior

Header Property Text should be displayed if its not empty

### How to reproduce it (as minimally and precisely as possible)

add Toggle Button to app, set its Header Property as shown above

### Workaround

place a additional TextBox beneath it for the Header Text

### Works on UWP/WinUI

None

### Affected platforms

Skia (WPF), Skia (Linux X11), Skia (macOS), Skia (Linux Framebuffer), Skia (GTK)

### IDE

Visual Studio 2022

### IDE version

17.12.3

### Anything else we need to know?

Using Material Design not Fluent

**Comment by jeromelaban** [comment]
This looks like a material theme specific issue, which _may_ not support header?

**Comment by Xiaoy312** [comment]
This is indeed by design. There is no particular text/label field tied to a [Switch for Material Design](https://m3.material.io/components/switch/overview).
You have much better control with a separate TextBlock that you can explicitly define its relative position(top,down,left,right) to the toggle-switch and its styles(font, color, size, etc).

**Comment by DevTKSS** [comment]
![Screenshot 2024-12-16 200029](https://github.com/user-attachments/assets/d9ce4dbd-00d2-4dd2-91b8-82b9e4f16dd8)
then the Reference/UI/ToggleSwitch should be updated with this detail. it is telling its supported for "all plattforms" which is not stating the theme choosage

**Comment by Xiaoy312** [comment]
So the specific dependency property have been implemented and do work, as you have noticed for the "fluent" style.
It is just a for the "material design" style, we choose to not use it, because there is no convention on the placement of said header, and there is other easier way of accomplishing the same result.
If you want to still use the header property, you can take the existing ToggleSwitch material style template, and edit to add a ContentPresenter for the header.
material style: https://github.com/unoplatform/Uno.Themes/blob/master/src/library/Uno.Material/Styles/Controls/v2/ToggleSwitch.xaml
fluent style: https://github.com/unoplatform/uno/blob/master/src/Uno.UI.FluentTheme.v2/Resources/Version2/PriorityDefault/ToggleSwitch_themeresources.xaml
