### ISSUE TITLE
NavigationViewItems colorings not overridable

### ISSUE THREAD

**Issue by igiona** [unoplatform/Uno.Themes#963]
## Current behavior
```
<muxc:NavigationView>
  <NavigationView.Resources>
    <!-- Menu item -->
    <SolidColorBrush x:Key="MaterialNavigationViewItemBackgroundSelected" Color="Pink" /> 
    <SolidColorBrush x:Key="MaterialNavigationViewItemBackgroundPressed" Color="Orange" /> 
    <SolidColorBrush x:Key="MaterialNavigationViewItemBackgroundPointerOver" Color="LightGreen" /> 
    <SolidColorBrush x:Key="MaterialNavigationViewItemBackgroundDisabled" Color="Gray" /> 
    <SolidColorBrush x:Key="MaterialNavigationViewItemRippleFeedback" Color="Orange" />
    
    <!-- separator -->
    <SolidColorBrush x:Key="NavigationViewItemSeparatorForeground" Color="white" /> 
    <SolidColorBrush x:Key="TopNavigationViewItemSeparatorForeground" Color="white" />

    <!-- pane -->
    <SolidColorBrush x:Key="NavigationViewExpandedPaneBackground" Color="DarkBlue" />
    <SolidColorBrush x:Key="NavigationViewDefaultPaneBackground" Color="LightBlue" />
    
    <!-- burger menu --> 

    <SolidColorBrush x:Key="NavigationViewItemBackground" Color="Orange" /> 
    <SolidColorBrush x:Key="NavigationViewButtonBackground" Color="Yellow" /> 
    <SolidColorBrush x:Key="NavigationViewButtonForegroundPointerOver" Color="red"/> 
    <SolidColorBrush x:Key="NavigationViewButtonForegroundPressed" Color="green"/> 
    <SolidColorBrush x:Key="NavigationViewButtonBackgroundPointerOver" Color="Magenta" /> 
    <SolidColorBrush x:Key="NavigationViewButtonBackgroundPressed" Color="LightCoral" /> 
    <SolidColorBrush x:Key="NavigationViewButtonBackgroundDisabled" Color="Gray" />
    <SolidColorBrush x:Key="NavigationViewButtonForegroundDisabled" Color="White" />

  </NavigationView.Resources>
  <muxc:NavigationView.MenuItems>
    <muxc:NavigationViewItemSeparator />
    <muxc:NavigationViewItem Content="Dashboard" uen:Region.Name="Dashboard">
      <muxc:NavigationViewItem.Icon>
        <PathIcon Data="{StaticResource Icon_Home}" Foreground="{ThemeResource SecondaryVariantDarkBrush}" />
      </muxc:NavigationViewItem.Icon>
    </muxc:NavigationViewItem>
    <muxc:NavigationViewItem Content="Sensors" uen:Region.Name="Sensors">
      <muxc:NavigationViewItem.Icon>
        <PathIcon Data="{StaticResource Icon_Show_Chart}" Foreground="{ThemeResource SecondaryVariantDarkBrush}" />
      </muxc:NavigationViewItem.Icon>
    </muxc:NavigationViewItem>
  </muxc:NavigationView.MenuItems>
</muxc:NavigationView>

```

When using the <muxc:NavigationView > element in a WASM or WinUi application, it's not possible to change the menu items Selected, Pressed, PointerOver, Disabled, RippleFeedback within the <NavigationView.Resources>, hence locally to the menu element (not globally for the whole app).
The elements listed under "" are not affecting the UI.

## Expected behavior

Changing the MaterialNavigationViewItem* SolidColorBrush shall change the  color of the corresponding element in the UI.
Ideally, it would be good to be able to change also the foreground  and background color via SolidColorBrush override.
NOTE: Currently I have to use a custom style:
```
    <Style TargetType="muxc:NavigationViewItem" BasedOn="{StaticResource MaterialNavigationViewItemStyle}" >
      <Setter Property="Foreground" Value="{ThemeResource OnSecondaryColor}" />
      <Setter Property="Background" Value="{ThemeResource SecondaryVariantLightBrush}" />
    </Style>
```

## How to reproduce it (as minimally and precisely as possible)

Add the above mentioned XAML snipped into a WinUi App, and run it.
The MenuItem color will not match the one defined via MaterialNavigationViewItem*

## Anything else we need to know?

Additionally, it's to me not really clear why `NavigationViewItemBackground` does change the background color of the burger-menu icon, whereare `NavigationViewButtonBackground` seems not to have any effect.

**Comment by Xiaoy312** [comment]
context: // internal discussion thread
https://teams.microsoft.com/l/message/19:pDloX3pnLcwGELCyHbJl1pGXdRq0i348biXn3ZVXGI41@thread.tacv2/1676927305188?tenantId=a297d6c0-b635-41a3-b1e3-558efe71e413&groupId=bef7e710-0b2c-440b-b00d-466ef6bcda07&parentMessageId=1676927305188

**Comment by agneszitte** [comment]
To be double-checked if it is correctly fixed with lightweight styling latest changes

**Comment by silviuo** [comment]
I tested by applying the following resources to the NavigationView inside the Nav View Sample Page:

![image](https://github.com/unoplatform/Uno.Themes/assets/10283398/edc3202b-2432-4d59-989f-e3b30b64e389)

						
These are the results:

UWP:

![image](https://github.com/unoplatform/Uno.Themes/assets/10283398/4833be7c-a077-481d-b2ea-3a43037c0ec2)

![image](https://github.com/unoplatform/Uno.Themes/assets/10283398/0b82757c-efc1-484a-b143-2d6430b6b755)

Notes:

`NavigationViewExpandedPaneBackground` did not make any change because the key doesn't exist in v2. There is only [MaterialMUXNavigationViewExpandedPaneBackground](https://github.com/unoplatform/Uno.Themes/blob/8b41c7d874af41a4ed0bf8a5ddfd25d9933e46b8/src/library/Uno.Material/Styles/Controls/v1/NavigationView/NavigationView_MUX.xaml#L37) under v1. 

`NavigationViewDefaultPaneBackground` did not make any change (first screenshots with white background). `NavigationViewPaneBackground` worked to change the background though (LightBlue visible in last couple of screenshots).

For the separator to be visible, I changed its MinHeight [here](https://github.com/unoplatform/Uno.Themes/blob/8b41c7d874af41a4ed0bf8a5ddfd25d9933e46b8/src/library/Uno.Material/Styles/Controls/v2/NavigationView.xaml#L3746).

I am closing this bug since brushes are now overridable locally.
